### ISSUE TITLE
Can't access off-screen columns in table when force_full_width=True

### ISSUE THREAD

**Issue by currivan** [facebookresearch/hiplot#16] opened 2020-02-04 22:10 UTC
When there are too many columns to display on the screen, there's no way to access the missing ones in the table. It would be helpful if displayed columns could be toggled off or resized, or if reordering the plot columns reordered the table.

**Comment by danthe3rd** [comment] 2020-02-05 09:58
Hi :)
This will be fixed in the next version `0.1.3`

**Comment by pavsidhu** [comment] 2020-02-23 12:20
I believe this still may be an issue in 0.1.4, I'm unable to scroll through columns, I can only see 6 in total?

**Comment by danthe3rd** [comment] 2020-02-23 17:24
Reopening. I can't reproduce tho... I tried with this code, and I have an horizontal scroll bar that I can use.
```
import hiplot as hip
data = [{'dropout':0.1, 'lr': 0.001, 'loss': 10.0, 'optimizer': 'SGD', 'a'*100: 'a'},
        {'dropout':0.15, 'lr': 0.01, 'loss': 3.5, 'optimizer': 'Adam', 'b'*100: 'b'},
        {'dropout':0.3, 'lr': 0.1, 'loss': 4.5, 'optimizer': 'Adam', 'c'*100: 'c'}]
hip.Experiment.from_iterable(data).display(force_full_width=True)
```
![image](https://user-images.githubusercontent.com/43445237/75116522-8cae2800-5669-11ea-9bab-99c7464148ae.png)

Can you elaborate on your setup?

**Comment by danthe3rd** [comment] 2020-04-14 12:37
Closing because inactive

**Comment by ItaiShchorry** [comment] 2021-06-14 07:25
Also experiencing this issue - can't view more than 7-9 columns (using jupyterlab)

**Comment by danthe3rd** [comment] 2021-06-14 07:48
> Also experiencing this issue - can't view more than 7-9 columns (using jupyterlab)

I think I can reproduce it now - the left-most and right-most columns are hidden:

```python
import hiplot as hip
from hiplot.fetchers_demo import demo

demo().display(force_full_width=True)
```

![image](https://user-images.githubusercontent.com/43445237/121856984-68aaa600-ccf5-11eb-8b32-44e9dd0e5c0a.png)

The problem is that the `force_full_width` options is a hack, which is only supported on Jupyter Notebooks. I should remove it for Jupyter lab (it's also not needed, because the width is much larger than on notebooks).

@ItaiShchorry can you confirm that setting `force_full_width=False` fixes it?

**Comment by ItaiShchorry** [comment] 2021-06-14 08:18
Looks like it does =) from my understanding, high cardinality columns were automatically dropped so didn't notice the correct behavior at first.
![image](https://user-images.githubusercontent.com/17413213/121861041-220f7880-cd02-11eb-8ac5-11d4b1b96336.png)


![image](https://user-images.githubusercontent.com/17413213/121860937-04daaa00-cd02-11eb-832d-1f8cb38c308f.png)

**Closed** 2021-06-14 08:52 UTC
Labels: bug
