### ISSUE TITLE
HiPlot not displaying // Version 0.1.8.post2 broken on notebooks

### ISSUE THREAD

**Issue by Erick7451** [facebookresearch/hiplot#58] opened 2020-04-17 01:44 UTC
When running below command:
```
import hiplot as hip
data = [{'dropout':0.1, 'lr': 0.001, 'loss': 10.0, 'optimizer': 'SGD'},
        {'dropout':0.15, 'lr': 0.01, 'loss': 3.5, 'optimizer': 'Adam'}]
hip.Experiment.from_iterable(data).display()
```
HiPlot graph never loads with following output
```
Loading HiPlot...
<hiplot.ipython.IPythonExperimentDisplayed at 0x1df01706b70>
```

### Reproduction
```
(new_interpreter) C:\Users\erick>pip install hiplot
Collecting hiplot
  Using cached hiplot-0.1.8.post2-py3-none-any.whl (335 kB)
Requirement already satisfied: beautifulsoup4 in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from hiplot) (4.9.0)
Requirement already satisfied: flask-compress in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from hiplot) (1.4.0)
Requirement already satisfied: flask in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from hiplot) (1.1.2)
Requirement already satisfied: ipython>=7.0.1 in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from hiplot) (7.13.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from beautifulsoup4->hiplot) (2.0)
Requirement already satisfied: click>=5.1 in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from flask->hiplot) (7.1.1)
Requirement already satisfied: Werkzeug>=0.15 in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from flask->hiplot) (0.16.0)
Requirement already satisfied: Jinja2>=2.10.1 in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from flask->hiplot) (2.11.2)
Requirement already satisfied: itsdangerous>=0.24 in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from flask->hiplot) (1.1.0)
Requirement already satisfied: decorator in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from ipython>=7.0.1->hiplot) (4.4.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from ipython>=7.0.1->hiplot) (3.0.5)
Requirement already satisfied: jedi>=0.10 in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from ipython>=7.0.1->hiplot) (0.17.0)
Requirement already satisfied: pygments in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from ipython>=7.0.1->hiplot) (2.6.1)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from ipython>=7.0.1->hiplot) (0.4.3)
Requirement already satisfied: setuptools>=18.5 in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from ipython>=7.0.1->hiplot) (46.1.3.post20200325)
Requirement already satisfied: traitlets>=4.2 in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from ipython>=7.0.1->hiplot) (4.3.3)
Requirement already satisfied: pickleshare in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from ipython>=7.0.1->hiplot) (0.7.5)
Requirement already satisfied: backcall in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from ipython>=7.0.1->hiplot) (0.1.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from Jinja2>=2.10.1->flask->hiplot) (1.1.1)
Requirement already satisfied: wcwidth in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.0.1->hiplot) (0.1.9)
Requirement already satisfied: parso>=0.7.0 in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from jedi>=0.10->ipython>=7.0.1->hiplot) (0.7.0)
Requirement already satisfied: ipython-genutils in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from traitlets>=4.2->ipython>=7.0.1->hiplot) (0.2.0)
Requirement already satisfied: six in c:\users\erick\miniconda3\envs\new_interpreter\lib\site-packages (from traitlets>=4.2->ipython>=7.0.1->hiplot) (1.14.0)
Installing collected packages: hiplot
Successfully installed hiplot-0.1.8.post2
```

**Comment by danthe3rd** [comment] 2020-04-17 06:59
Hi @Erick7451 

I just published the version 0.1.8, which changes how we render visualizations in notebooks, which might cause this issue I suspect. Can you precise your setup: OS, browser, notebook used (jupyter notebook? jupyter labs? ..)?
Could you also do the following to help me figure out what's going on:
1. Restart kernel + clear output
2. Save notebook
3. Reload page
4. Open web console (https://support.monday.com/hc/en-us/articles/360002197259-How-to-Open-the-Developer-Console-in-your-Browser)
5. Run the cell with the hiplot call
6. Wait 10 seconds and send me a screenshot of the page + the web console

As a temporary workaround, version `0.1.7` should work (`pip install hiplot==0.1.7.post3`).

Thank you again for the bug report

**Comment by avant1** [comment] 2020-04-17 13:51
I've noticed similar issue with latest version (`hiplot-0.1.8.post2`). Downgrade to `0.1.7.post3` as @danthe3rd suggested resolves the issue.

Here is my setup:
- OS: Windows 10
- browser: MS Edge (Chromium-based browser)
- jupyter notebook with a couple of [nbextensions](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html) enabled

Here is JS error stacktrace:
![image](https://user-images.githubusercontent.com/2902785/79575770-ef043180-80ca-11ea-8b6d-966b039320f1.png)

<details>
  <summary>Text version inside</summary>
  
  
  ```javascript
Uncaught SyntaxError: missing ) after argument list
    at DOMEval (jquery.min.js:124)
    at domManip (jquery.min.js:5945)
    at jQuery.fn.init.append (jquery.min.js:6081)
    at OutputArea._safe_append (outputarea.js:457)
    at OutputArea.append_display_data (outputarea.js:660)
    at OutputArea.append_output (outputarea.js:346)
    at OutputArea.handle_output (outputarea.js:257)
    at output (codecell.js:395)
    at Kernel._handle_output_message (kernel.js:1197)
    at proxy (jquery.min.js:10502)
  ```
  
</details>

**Comment by Erick7451** [comment] 2020-04-17 15:38
Thank you for your reply @danthe3rd 

Below is my setup:
* Windows
* Chrome
* Jupyter Notebook
* Python 3.6.8

Command:
![image](https://user-images.githubusercontent.com/40013722/79586483-cb26f880-8096-11ea-9480-5d908357294b.png)

Console Output:
![image](https://user-images.githubusercontent.com/40013722/79586596-f3aef280-8096-11ea-9980-a96dd9dac49c.png)

As @avant1, downgrading to ```0.1.7.post3``` resolved the issue. 

Thank you for the temporary fix! @danthe3rd

**Comment by danthe3rd** [comment] 2020-04-17 15:43
Thanks for the clarification. It seems to be a problem with the newest release indeed. I've managed to reproduce the issue, and will publish a fix on monday hopefully.
In between, I've unpublished the versions `0.1.8.post1` and `0.1.8.post2` from pypi.

**Comment by danthe3rd** [comment] 2020-04-18 14:59
Closing because the last version pushed should work as intended :) Please update with `pip install -U hiplot`

**Closed by danthe3rd** 2020-04-18 14:59 UTC
Labels: bug
